/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package tk.oknctict.izanagi.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTMTS = 1;
  public int JJTBLOCK = 2;
  public int JJTWHILEBLOCK = 3;
  public int JJTFUNCBLOCK = 4;
  public int JJTARGUMENTS = 5;
  public int JJTARGUMENT = 6;
  public int JJTSTMT = 7;
  public int JJTDEFFUNC = 8;
  public int JJTCALLFUNC = 9;
  public int JJTIFSTMT = 10;
  public int JJTWHILESTMT = 11;
  public int JJTSELECTSTMT = 12;
  public int JJTPARTSSTMT = 13;
  public int JJTDIMSTMT = 14;
  public int JJTBREAKSTMT = 15;
  public int JJTCONTINUESTMT = 16;
  public int JJTPRINTSTMT = 17;
  public int JJTRETURNSTMT = 18;
  public int JJTVOID = 19;
  public int JJTASSIGN = 20;
  public int JJTADDASSIGN = 21;
  public int JJTSUBASSIGN = 22;
  public int JJTMULASSIGN = 23;
  public int JJTDIVASSIGN = 24;
  public int JJTMODASSIGN = 25;
  public int JJTPOWASSIGN = 26;
  public int JJTBAND = 27;
  public int JJTBOR = 28;
  public int JJTEQ = 29;
  public int JJTNEQ = 30;
  public int JJTGE = 31;
  public int JJTGT = 32;
  public int JJTLE = 33;
  public int JJTLT = 34;
  public int JJTADD = 35;
  public int JJTSUB = 36;
  public int JJTMUL = 37;
  public int JJTDIV = 38;
  public int JJTMOD = 39;
  public int JJTPOWER = 40;
  public int JJTAND = 41;
  public int JJTOR = 42;
  public int JJTNOT = 43;
  public int JJTUNIEXPR = 44;
  public int JJTINTEGER = 45;
  public int JJTFLOAT = 46;
  public int JJTSTRING = 47;
  public int JJTVAR = 48;
  public int JJTREFVAR = 49;
  public int JJTSUBSCRIPT = 50;
  public int JJTFUNCNAME = 51;
  public int JJTIDENTIFIER = 52;


  public String[] jjtNodeName = {
    "Start",
    "Stmts",
    "Block",
    "WhileBlock",
    "FuncBlock",
    "Arguments",
    "Argument",
    "Stmt",
    "DefFunc",
    "CallFunc",
    "IfStmt",
    "WhileStmt",
    "SelectStmt",
    "PartsStmt",
    "DimStmt",
    "BreakStmt",
    "ContinueStmt",
    "PrintStmt",
    "ReturnStmt",
    "void",
    "Assign",
    "AddAssign",
    "SubAssign",
    "MulAssign",
    "DivAssign",
    "ModAssign",
    "PowAssign",
    "BAnd",
    "BOr",
    "Eq",
    "NEq",
    "Ge",
    "Gt",
    "Le",
    "Lt",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Mod",
    "Power",
    "And",
    "Or",
    "Not",
    "UniExpr",
    "Integer",
    "Float",
    "String",
    "Var",
    "RefVar",
    "Subscript",
    "FuncName",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=ae1c945165aca64d1c4b5efd235e8d4e (do not edit this line) */
